airports:
  [
    "ORY",
    "NCE",
    "LYS",
    "TLS",
    "MRS",
    "BSL",
    "BOD",
    "NTE",
    "BVA",
    "RUN",
    "PTP",
    "LIL",
    "FDF",
    "MPL",
  ]

topic: captors/pressure
qos: 0
timeBtwData: 5
clientID: pressure_captor
nature: pressure
